CREATE DATABASE DATA_WAREHOUSE_PROJECT;

USE DATA_WAREHOUSE_PROJECT;

CREATE TABLE DIM_TIME(
	TIME_ID INT NOT NULL PRIMARY KEY,
	YEAR INT NOT NULL,
	TRIMESTER INT NOT NULL,
	MONTH INT NOT NULL,
	DAY INT NOT NULL,
	FULL_DATE VARCHAR(50) NOT NULL
);

CREATE TABLE DIM_CATEGORY(
	CATEGORY_ID INT NOT NULL PRIMARY KEY,
	CATEGORY VARCHAR(100) NOT NULL
);

CREATE TABLE DIM_DEVELOPER(
	DEVELOPER_ID INT NOT NULL PRIMARY KEY,
	NAME NVARCHAR(100) NOT NULL,
	WEBSITE VARCHAR(300), /*PUEDE SER NULO*/
	EMAIL VARCHAR(100) /*PUEDE SER NULO*/
);

CREATE TABLE DIM_APP(
	APP_ID INT NOT NULL PRIMARY KEY,
	GP_IDENTIFIER VARCHAR(300) NOT NULL,
	NAME NVARCHAR(100) NOT NULL,
	RATING INT, /*PUEDE SER NULO*/
	RATING_COUNT INT /*PUEDE SER NULO*/
);

CREATE TABLE H_APP(
	APP_ID INT NOT NULL,
	FOREIGN KEY (APP_ID) REFERENCES DIM_APP(APP_ID),
	DEVELOPER_ID INT NOT NULL,
	FOREIGN KEY (DEVELOPER_ID) REFERENCES DIM_DEVELOPER(DEVELOPER_ID),
	CATEGORY_ID INT NOT NULL,
	FOREIGN KEY (CATEGORY_ID) REFERENCES DIM_CATEGORY(CATEGORY_ID),
	TIME_ID INT NOT NULL,
	FOREIGN KEY (TIME_ID) REFERENCES DIM_TIME(TIME_ID),
	INSTALLS VARCHAR(50), /*PUEDE SER NULO*/
	MINIMUM_INSTALLS BIGINT, /*PUEDE SER NULO*/
	MAXIMUM_INSTALLS BIGINT, /*PUEDE SER NULO*/
	PRIMARY KEY (APP_ID, DEVELOPER_ID, CATEGORY_ID, TIME_ID)
);

CREATE TABLE TEMP_TIME(
	TIME_ID INT NOT NULL PRIMARY KEY,
	TIME VARCHAR(20) NOT NULL
);


CREATE TRIGGER INSTEAD_INSERT_APP
	ON DIM_APP INSTEAD OF INSERT
AS
	BEGIN
		SET NOCOUNT ON;
		INSERT INTO DIM_APP
		SELECT APP_ID, GP_IDENTIFIER, CONVERT(NVARCHAR, NAME), RATING, RATING_COUNT FROM INSERTED;
	END
GO

CREATE TRIGGER INSTEAD_INSERT_DEVELOPER
	ON DIM_DEVELOPER INSTEAD OF INSERT
AS
	BEGIN
		SET NOCOUNT ON;
		INSERT INTO DIM_DEVELOPER
		SELECT DEVELOPER_ID, CONVERT(NVARCHAR, NAME), WEBSITE, EMAIL FROM INSERTED;
	END
GO